```yaml
name: Build
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.0

      - name: Prep & Deep Fix
        run: |
          rm -rf android
          flutter create --platforms android --project-name mic_app .

          python3 -c "
import re

with open('android/app/build.gradle', 'r') as f:
    c = f.read()
c = re.sub(r'minSdk\s*=\s*\S+', 'minSdk = 21', c)
c = re.sub(r'(android\s*\{)', r'\1\n    packagingOptions {\n        resources {\n            noCompress += [\".tflite\"]\n        }\n    }', c, count=1)
c = re.sub(r'(defaultConfig\s*\{)', r'\1\n        ndk { abiFilters \"armeabi-v7a\", \"arm64-v8a\" }', c, count=1)
with open('android/app/build.gradle', 'w') as f:
    f.write(c)

with open('android/app/src/main/AndroidManifest.xml', 'r') as f:
    m = f.read()
m = m.replace('<application', '    <uses-permission android:name=\"android.permission.CAMERA\" />\n    <uses-feature android:name=\"android.hardware.camera\" />\n    <application', 1)
with open('android/app/src/main/AndroidManifest.xml', 'w') as f:
    f.write(m)
"

          mkdir -p assets
          printf 'name: mic_app\nenvironment:\n  sdk: ">=3.0.0 <4.0.0"\n  flutter: ">=3.19.0"\ndependencies:\n  flutter:\n    sdk: flutter\n  camera: ^0.11.0\n  tflite_v2: ^1.0.0\nflutter:\n  uses-material-design: true\n  assets:\n    - assets/labels.txt\n    - assets/model.tflite\n' > pubspec.yaml

      - name: Check Assets
        run: |
          if [ ! -f "assets/model.tflite" ]; then echo "ERRORE: assets/model.tflite mancante!"; exit 1; fi
          if [ ! -f "assets/labels.txt" ]; then echo "ERRORE: assets/labels.txt mancante!"; exit 1; fi
          echo "Asset check OK"

      - name: Build APK
        run: |
          flutter clean
          flutter pub get
          flutter build apk --release --no-tree-shake-icons

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
```
