concurrency:
  name: Flutter Build
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Rinominazione e Hard Reset
        run: |
          # Forza il nuovo nome su tutto il progetto
          flutter create . --project-name mic_app --overwrite --platforms android
          
          # Fix SDK 21 per la fotocamera
          sed -i 's/minSdkVersion [0-9]\+/minSdkVersion 21/g' android/app/build.gradle

      - name: Build APK
        run: |
          flutter pub get
          flutter build apk --release
